import type { Locale } from "./i18n.js";
import {
  getSansIrCopy,
  sansArtifactCards,
  sansScenarioCards,
  summarizeSansIrSurface
} from "./sansIrData.js";

function Metric({ label, value, detail }: { label: string; value: string; detail: string }) {
  return (
    <article className="metric">
      <span>{label}</span>
      <strong>{value}</strong>
      <small>{detail}</small>
    </article>
  );
}

export function SansIrScenarioSection({ locale }: { locale: Locale }) {
  const copy = getSansIrCopy(locale);
  const summary = summarizeSansIrSurface();
  const labels =
    locale === "zh"
      ? {
          routes: "IR 路线",
          routesDetail: "磁盘、日志、处置",
          correction: "自我纠错",
          correctionDetail: "弱证据结论会被降级",
          status: "准确性状态",
          statusDetail: "confirmed / rejected / inferred",
          replay: "复现命令",
          replayDetail: "本地 runner + 提交检查",
          trigger: "触发",
          unsafe: "危险动作",
          evidence: "必须保留的证据",
          outcome: "门禁结论",
          correctionLabel: "纠错动作"
        }
      : {
          routes: "IR routes",
          routesDetail: "disk, logs, containment",
          correction: "self-correction",
          correctionDetail: "weak claims are downgraded",
          status: "accuracy statuses",
          statusDetail: "confirmed / rejected / inferred",
          replay: "replay commands",
          replayDetail: "local runner + submission check",
          trigger: "trigger",
          unsafe: "unsafe action",
          evidence: "required evidence",
          outcome: "gate decision",
          correctionLabel: "correction"
        };

  return (
    <section className="splunk-contest-panel" aria-label={copy.kicker}>
      <div className="splunk-contest-copy">
        <span>{copy.kicker}</span>
        <h2>{copy.title}</h2>
        <p>{copy.body}</p>
      </div>
      <div className="splunk-contest-metrics">
        <Metric label={labels.routes} value={String(summary.irRoutes)} detail={labels.routesDetail} />
        <Metric label={labels.correction} value={String(summary.selfCorrections)} detail={labels.correctionDetail} />
        <Metric label={labels.status} value={String(summary.accuracyStatuses)} detail={labels.statusDetail} />
        <Metric label={labels.replay} value={String(summary.replayCommands)} detail={labels.replayDetail} />
      </div>
      <div className="splunk-scenario-grid">
        {sansScenarioCards.map((card) => (
          <article className="splunk-scenario-card is-active" key={card.id}>
            <h3>{card.title[locale]}</h3>
            <dl>
              <div>
                <dt>{labels.trigger}</dt>
                <dd>{card.trigger[locale]}</dd>
              </div>
              <div>
                <dt>{labels.unsafe}</dt>
                <dd>{card.unsafeAction[locale]}</dd>
              </div>
              <div>
                <dt>{labels.evidence}</dt>
                <dd>{card.evidence[locale]}</dd>
              </div>
              <div>
                <dt>{labels.correctionLabel}</dt>
                <dd>{card.correction[locale]}</dd>
              </div>
            </dl>
            <b>{card.outcome[locale]}</b>
          </article>
        ))}
      </div>
    </section>
  );
}

export function SansReplaySection({ locale }: { locale: Locale }) {
  const copy =
    locale === "zh"
      ? {
          kicker: "本地复现路径",
          title: "评委不用相信截图，可以直接跑同一条证据链。",
          body: "这组 artifact 都来自 `npm run sans:check`。如果本机没有 SIFT 工具，runner 会明确记录 fixture-local 模式；如果在 SIFT Workstation 上运行，命令契约可以映射到真实工具。"
        }
      : {
          kicker: "local replay path",
          title: "Judges do not have to trust screenshots. They can run the same evidence chain.",
          body:
            "These artifacts are generated by `npm run sans:check`. Without SIFT binaries, the runner records fixture-local mode; on a SIFT Workstation, the command contract maps to real tools."
        };

  return (
    <section className="splunk-companion-panel" aria-label={copy.kicker}>
      <div className="splunk-companion-copy">
        <span>{copy.kicker}</span>
        <h2>{copy.title}</h2>
        <p>{copy.body}</p>
      </div>
      <div className="splunk-deployment-grid">
        {sansArtifactCards.map((card) => (
          <article className="splunk-deployment-card is-active" key={card.id}>
            <h3>{card.title[locale]}</h3>
            <dl>
              <div>
                <dt>{locale === "zh" ? "路径" : "path"}</dt>
                <dd>{card.path}</dd>
              </div>
              <div>
                <dt>{locale === "zh" ? "证明" : "proof"}</dt>
                <dd>{card.proof[locale]}</dd>
              </div>
              <div>
                <dt>{locale === "zh" ? "命令" : "command"}</dt>
                <dd>{card.command}</dd>
              </div>
            </dl>
          </article>
        ))}
      </div>
    </section>
  );
}
